apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "nr-ebpf-agent.otelcollecter.name" . }}
  labels:
    {{- include "newrelic.common.labels" . | nindent 4 }}
rules:
- apiGroups:
  - ""
  resources:
  - pods
  - namespaces
  - nodes
  - services
  - endpoints
  verbs:
  - get
  - watch
  - list
- apiGroups:
  - "apps"
  resources:
  - replicasets
  verbs:
  - get
  - watch
  - list
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "nr-ebpf-agent.otelcollecter.name" . }}
  labels:
    {{- include "newrelic.common.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "nr-ebpf-agent.otelcollecter.name" . }}
subjects:
- kind: ServiceAccount
  name: {{ include "nr-ebpf-agent.collecter.name" . }}
  namespace: '{{ .Release.Namespace }}'